ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS seo_canonical TEXT;
ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS seo_robots VARCHAR(80) DEFAULT 'index,follow';
ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS schema_type VARCHAR(80);
ALTER TABLE cms_pages ADD COLUMN IF NOT EXISTS schema_json JSONB DEFAULT '{}'::jsonb;

ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS seo_canonical TEXT;
ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS seo_robots VARCHAR(80) DEFAULT 'index,follow';
ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS schema_type VARCHAR(80);
ALTER TABLE cms_sections ADD COLUMN IF NOT EXISTS schema_json JSONB DEFAULT '{}'::jsonb;

ALTER TABLE news ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS seo_canonical TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS seo_robots VARCHAR(80) DEFAULT 'index,follow';
ALTER TABLE news ADD COLUMN IF NOT EXISTS schema_type VARCHAR(80);
ALTER TABLE news ADD COLUMN IF NOT EXISTS schema_json JSONB DEFAULT '{}'::jsonb;

ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_canonical TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_robots VARCHAR(80) DEFAULT 'index,follow';
ALTER TABLE products ADD COLUMN IF NOT EXISTS schema_type VARCHAR(80);
ALTER TABLE products ADD COLUMN IF NOT EXISTS schema_json JSONB DEFAULT '{}'::jsonb;
